Adding Evidential and Mean-Variance (MVE) Uncertainty Predictors
chemprop/chemprop pull request #1061
Opened 2024-10-17 18:16 UTC by akshatzalte

## Description
This PR implements the MVE and Evidential uncertainty predictors.
Adding evidential uncertainty predictors: total, epistemic, and aleatoric based on: Amini, A.; Schwarting, W.; Soleimany, A.; Rus, D. "Deep Evidential Regression". NeurIPS, 2020. 

Added these to the `UncertaintyPredictor` module. The notebook `chemprop/examples/uncertainty.ipynb` is modified to test these predictors.

## Example / Current workflow
```
from chemprop.uncertainty.predictor import EvidentialAleatoricPredictor
predictor = EvidentialAleatoricPredictor()
predss, uncss = predictor(test_loader, models, trainer)

2024-10-17 19:59 UTC, shihchengli requested changes

2024-10-17 19:59 UTC, shihchengli commented on examples/uncertainty.ipynb
I think we can remove this change here. I will open another PR to make this notebook more general and comprehensive.

2024-10-17 19:59 UTC, shihchengli commented on chemprop/uncertainty/predictor.py
> +import torch._tensor
```suggestion
```

2024-10-17 20:08 UTC, shihchengli commented on chemprop/uncertainty/predictor.py
> +    Class that estimates prediction means and variances (MVE).
```suggestion
    Class that estimates prediction means and variances (MVE). [nix1994]_
    
    References
    ----------
    .. [nix1994] Nix, D. A.; Weigend, A. S. "Estimating the mean and variance of the target
        probability distribution." Proceedings of 1994 IEEE International Conference on Neural
        Networks, 1994 https://doi.org/10.1109/icnn.1994.374138
```

2024-10-18 17:17 UTC, akshatzalte commented
Notebook changes have been reverted and the binary classification Dirichlet is added.

2024-10-18 17:35 UTC, shihchengli commented
Can you do black formatting?

2024-10-19 02:56 UTC, shihchengli approved these changes

2024-10-19 02:59 UTC, merged