updated warning to logger
chemprop/chemprop pull request #1090
Opened 2024-10-28 20:57 UTC by twinbrian

proofread logger.info and changed all warning.warn to logger.warn (including notebooks)

2024-10-29 15:12 UTC, shihchengli requested changes

2024-10-30 18:58 UTC, twinbrian commented on examples/uncertainty.ipynb
> +      "/Users/brianli/Documents/chemprop/chemprop/models/model.py:288: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle m
Agree, fixed

2024-10-30 19:14 UTC, shihchengli commented on examples/uncertainty.ipynb
> +      "/Users/brianli/Documents/chemprop/chemprop/models/model.py:288: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle m
Can you also change this in the other modules (e.g., `chemprop/models/multi.py`, `chemprop/models/utils.py`)?

2024-10-31 14:13 UTC, shihchengli approved these changes

2024-11-07 17:26 UTC, merged