Adding checks for if MoleculeDataset has length zero to prevent index…
chemprop/chemprop pull request #260
Opened 2022-03-31 06:02 UTC by swansonk14

## Description
The split type `cv-no-test` crashes.

## Example / Current workflow
When running training with `--split_type cv-no-test`, chemprop crashes with an `IndexError: list index out of range`.

## Bugfix / Desired workflow
I fixed a few lines in `data/data.py` where the code was trying to index into `self._data[0]` without first checking whether `len(self._data) == 0`.

2022-04-04 19:29 UTC, cjmcgill commented on chemprop/data/data.py
>          """
Oops left out the description
```suggestion
        """
        Returns indications of whether the targets associated with each molecule are greater-than inequalities.
        
        :return: A list of lists of booleans indicating whether the targets in those positions are greater-than inequality targets.
        """
```

2022-04-04 19:30 UTC, cjmcgill commented on chemprop/data/data.py
>          """
```suggestion
        """
        Returns indications of whether the targets associated with each molecule are less-than inequalities.
        
        :return: A list of lists of booleans indicating whether the targets in those positions are less-than inequality targets.
        """
```

2022-04-04 19:32 UTC, cjmcgill commented
Seems like it parallels with how other missing features are handled elsewhere in the code. I also think that None would be the right output for here because the default state for a dataset is not to have any gt_targets or lt_targets. Returning empty sets implies that if there was data, we would have that information.

2022-04-04 19:33 UTC, cjmcgill approved these changes
Good by me once @davidegraff's concern is addressed.

2022-04-04 19:50 UTC, davidegraff commented
but then how do you differentiate between the case that a client code fails because there are *no data* vs `[gt/lt]_targets` simply not being set? It correct to say that we **know** the `[gt/lt]_targets` of an empty dataset: they're also an empty set

2022-04-04 20:10 UTC, cjmcgill commented
Seems fine to say that gt/lt is None unless assigned otherwise and that flagging that it's an empty dataset is better done elsewhere.

- [ ] But maybe there's a practical consideration here too. @swansonk14, in your splits where the empty sets are being generated, what gets done with those test sets? Do they go through operations where they need to have these attributes? In which case they may need to match the train set, and conditionally be None if the other is None and be empty if the other is filled. And should we also change the code so empty sets don't go through these operations in the first place?

2022-04-04 20:19 UTC, cjmcgill requested changes
The empty set question is still live.

2023-02-10 15:12 UTC, davidegraff commented
closing due to lack of activity. We can reopen this if the issue comes up again.

2023-02-10 15:12 UTC, closed without merging