Add Dirichlet Evidential Uncertainty Quantification
chemprop/chemprop pull request #423
Opened 2023-07-21 21:29 UTC by cjmcgill

## Description
Creates an option for `--uncertainty_method dirichlet`. This option allows for the calculation of dirichlet evidential uncertainty from predictions. Previously, classification methods trained with dirichlet loss function only provided the expected probability (excluding pure uncertainty). Now using this option, the dirichlet evidential uncertainty can be obtained in the prediction output.

Because this uncertainty output is not a confidence level, the calibration methods and evaluation methods available for calibration jobs normally are not available when `--uncertainty_method dirichlet`. However, calibration and evaluation can still be performed when the job is run with `--uncertainty_method classification` so that it's working with predicted confidence.

## Relevant issues
Solves issue in #413.
Supercedes PR #421

2023-07-21 21:30 UTC, cjmcgill commented
@muammar I'd appreciate it if you could try out this branch and see if it matches your expectations.

2023-07-26 17:56 UTC, muammar commented
The new modifications look good. I will try them this week. Thanks.

2023-09-27 15:58 UTC, muammar commented
Everything worked correctly for my use case. Thanks for your help.

2023-10-26 20:17 UTC, JacksonBurns requested changes
A couple small comments on the code itself. I have not validated the accuracy and am trusting the implementation and acceptance from @muammar.

2023-10-26 20:17 UTC, JacksonBurns commented on chemprop/uncertainty/uncertainty_calibrator.py
> +            raise NotImplementedError(
This should not be a `NotImplementedError`, but something more like a custom `InvalidConfigurationError` or I suggest just a plain old `RuntimeError`. See the [Python docs](https://docs.python.org/3/library/exceptions.html#NotImplementedError) - `NotImplementedError` is only for base classes with methods that are required to be overridden.

2023-10-26 20:17 UTC, JacksonBurns commented on chemprop/uncertainty/uncertainty_evaluator.py
> +            raise NotImplementedError(
Same comment as above.

2023-10-26 20:17 UTC, JacksonBurns commented on chemprop/uncertainty/uncertainty_predictor.py
> +                "Dirichlet evidential epistemic uncertainty is only compatible with classification dataset types."
Would be nice to see what we currently have with something like `f"Dirichlet ... types. Current dataset is of type {self.dataset_type}"`

2023-12-20 16:59 UTC, kevingreenman commented
@cjmcgill thanks for updating the error message. Do you agree with @JacksonBurns on the `NotImplementedError`s?

2023-12-20 17:28 UTC, cjmcgill commented
@kevingreenman @JacksonBurns I'm changing the `NotImplementedError` to `ValueError`. `ValueError` is what we've used for this kind of configuration/options error elsewhere and that would be more consistent.

I think that the custom error for configuration error is a good idea, but making that change would cover a lot of territory. There's many instances of ValueError for this and I think we're probably not the most interested in making that wide-ranging of a change in an unrelated PR.

2023-12-20 19:50 UTC, kevingreenman approved these changes

2023-12-20 19:55 UTC, JacksonBurns approved these changes
Looks good, thanks for addressing my comments. I agree with your thoughts on keeping this in scope as well.

2023-12-20 19:55 UTC, merged